name: Deploy Backend and Frontend

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    backend:
        runs-on: ubuntu-latest
        container: ghcr.io/railwayapp/cli:latest
        env:
          SVC_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
        steps:
          - uses: actions/checkout@v3
          - run: railway up --service=${{ secrets.SVC_ID }}

    frontend:
        name: Build & Deploy Frontend to Netlify
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '22.20.0'

            - name: Install dependencies
              run: npm install
              working-directory: ./frontend

            - name: Build
              run: npm run build
              working-directory: ./frontend

            - name: Deploy to Netlify
              uses: jsmrcaga/action-netlify-deploy@v2.0.0
              with:
                publish-dir: ./frontend/dist
                deploy-message: "Deploy from GitHub Actions"
                netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
                vite-api-url: ${{ secrets.VITE_API_URL }}
