name: Deploy Backend and Frontend

on:
    push:
        branches: [main]
    pull_request:
        types: [closed]
        branches: [main]

jobs:
    backend:
        name: Build & Deploy Backend to Fly.io
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Fly.io
              uses: superfly/flyctl-actions@1.4
              with:
                args: "auth token ${{ secrets.FLY_API_TOKEN }}"

            - name: Build and Deploy to Fly.io
              uses: superfly/flyctl-actions@1.4
              with:
                args: "deploy --remote-only"
              env:
                FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

    frontend:
        name: Build & Deploy Frontend to Netlify
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '18'

            - name: Install dependencies
              run: npm install
              working-directory: ./frontend

            - name: Build frontend
              run: npm run build
              working-directory: ./frontend

            - name: Deploy to Netlify
              uses: nwtgck/actions-netlify@v2.0
              with:
                publish-dir: ./frontend/dist
                production-deploy: true
                github-token: ${{ secrets.GITHUB_TOKEN }}
                deploy-message: "Deploy from GitHub Actions"
                netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}